#!/usr/bin/env python3
import argparse
import sys
import os
from argparse import RawTextHelpFormatter

class IceGen:
    __VERSION = "0.018"

    def __init__(self):
        self._parser = argparse.ArgumentParser(
            description="🧊 icegen: iCE40 CMake project generator",
            usage="icegen [-p] [-t [name]] [-d device] [-v]",
            formatter_class=RawTextHelpFormatter
        )
        self._setup_arguments()

    def _setup_arguments(self):
        self._parser.add_argument("-p", "--project", dest="project", metavar="", help="Create a new iCE40 project")
        self._parser.add_argument("-t", "--template", dest="template", nargs="?", const="sample", default="none", metavar="", help="Template name")
        self._parser.add_argument("-d", "--device", dest="device", default="up5k", metavar="", help="Target device")
        self._parser.add_argument("-v", "--version", action="store_true", help="Show version and exit")

    def parse_args(self):
        args = self._parser.parse_args()
        if args.version:
            print(f"icegen version {self.__VERSION}")
            sys.exit(0)
        if not args.project:
            self._parser.print_help()
            sys.exit(1)
        return args

    def write_root_build(self, base_dir, project_name):
        path = os.path.join(base_dir, "Build")  # no .sh extension
        with open(path, "w") as f:
            f.write("#!/usr/bin/env bash\n")
            f.write(f"# Build script for {project_name}\n")
            f.write("# Build gateware then software with CMake and move outputs under ./build.\n")
            f.write("# Supports flags: --sim, --prod, --test, --help\n\n")
            f.write("set -euo pipefail\n\n")
            f.write("ROOT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\n")
            f.write("GATEWARE_SRC=\"$ROOT_DIR/gateware\"\n")
            f.write("GATEWARE_BUILD=\"$GATEWARE_SRC/build\"\n")
            f.write("SOFTWARE_SRC=\"$ROOT_DIR/software\"\n")
            f.write("SOFTWARE_BUILD=\"$SOFTWARE_SRC/build\"\n")
            f.write("ROOT_BUILD=\"$ROOT_DIR/build\"\n\n")
            f.write("# Default flags (match software/CMakeLists.txt defaults)\n")
            f.write("BUILD_SIMULATION=ON\n")
            f.write("BUILD_PRODUCT=OFF\n")
            f.write("BUILD_TESTS=OFF\n\n")
            f.write("usage() \n")
            f.write("{\n")
            f.write("    cat <<EOF\n")
            f.write("Usage: $0 [options]\n\n")
            f.write("Options:\n")
            f.write("  --sim       Build in simulation mode (default)\n")
            f.write("  --prod      Build shared product library (.so/.dll)\n")
            f.write("  --test      Build unit tests with GoogleTest\n")
            f.write("  --help      Show this help\n")
            f.write("EOF\n")
            f.write("    exit 1\n")
            f.write("}\n\n")
            f.write("# Parse flags\n")
            f.write("for arg in \"$@\"; do\n")
            f.write("    case \"$arg\" in\n")
            f.write("        --sim)\n")
            f.write("            BUILD_SIMULATION=ON\n")
            f.write("            BUILD_PRODUCT=OFF\n")
            f.write("            BUILD_TESTS=OFF\n")
            f.write("            ;;\n")
            f.write("        --prod)\n")
            f.write("            BUILD_SIMULATION=OFF\n")
            f.write("            BUILD_PRODUCT=ON\n")
            f.write("            BUILD_TESTS=OFF\n")
            f.write("            ;;\n")
            f.write("        --test)\n")
            f.write("            BUILD_SIMULATION=OFF\n")
            f.write("            BUILD_PRODUCT=OFF\n")
            f.write("            BUILD_TESTS=ON\n")
            f.write("            ;;\n")
            f.write("        --help|-h)\n")
            f.write("            usage\n")
            f.write("            ;;\n")
            f.write("        *)\n")
            f.write("            echo \"Unknown option: $arg\"\n")
            f.write("            usage\n")
            f.write("            ;;\n")
            f.write("    esac\n")
            f.write("done\n\n")
            f.write("log() \n")
            f.write("{\n")
            f.write("    printf '[Build] %s\\n' \"$1\"\n")
            f.write("}\n\n")
            f.write("# Gateware build → no BUILD_* flags\n")
            f.write("run_cmake_build_gateware() \n")
            f.write("{\n")
            f.write("    local src_dir=\"$1\"\n")
            f.write("    local build_dir=\"$2\"\n")
            f.write("    local target=\"${3-}\"\n\n")
            f.write("    cmake -S \"$src_dir\" -B \"$build_dir\"\n\n")
            f.write("    if [[ -n \"$target\" ]]; then\n")
            f.write("        cmake --build \"$build_dir\" --target \"$target\"\n")
            f.write("    else\n")
            f.write("        cmake --build \"$build_dir\"\n")
            f.write("    fi\n")
            f.write("}\n\n")
            f.write("# Software build → pass BUILD_* flags\n")
            f.write("run_cmake_build_software() \n")
            f.write("{\n")
            f.write("    local src_dir=\"$1\"\n")
            f.write("    local build_dir=\"$2\"\n")
            f.write("    local target=\"${3-}\"\n\n")
            f.write("    cmake -S \"$src_dir\" -B \"$build_dir\" \\\n")
            f.write("        -DBUILD_SIMULATION=\"$BUILD_SIMULATION\" \\\n")
            f.write("        -DBUILD_PRODUCT=\"$BUILD_PRODUCT\" \\\n")
            f.write("        -DBUILD_TESTS=\"$BUILD_TESTS\"\n\n")
            f.write("    if [[ -n \"$target\" ]]; then\n")
            f.write("        cmake --build \"$build_dir\" --target \"$target\"\n")
            f.write("    else\n")
            f.write("        cmake --build \"$build_dir\"\n")
            f.write("    fi\n")
            f.write("}\n\n")
            f.write("move_dir() \n")
            f.write("{\n")
            f.write("    local source_dir=\"$1\"\n")
            f.write("    local dest_dir=\"$2\"\n\n")
            f.write("    if [[ ! -d \"$source_dir\" ]]; then\n")
            f.write("        log \"No artifacts to move from $source_dir\"\n")
            f.write("        return\n")
            f.write("    fi\n\n")
            f.write("    mkdir -p \"$(dirname \"$dest_dir\")\"\n")
            f.write("    mv \"$source_dir\" \"$dest_dir\"\n")
            f.write("}\n\n")
            f.write("# --- Build flow ---\n")
            f.write("log \"Configuring and building gateware\"\n")
            f.write("mkdir -p \"$ROOT_BUILD\"\n")
            f.write("mkdir -p \"$GATEWARE_BUILD\"\n")
            f.write("run_cmake_build_gateware \"$GATEWARE_SRC\" \"$GATEWARE_BUILD\" \"fpga\"\n")
            f.write("move_dir \"$GATEWARE_BUILD\" \"$ROOT_BUILD/gateware\"\n\n")
            f.write("log \"Configuring and building software\"\n")
            f.write("mkdir -p \"$SOFTWARE_BUILD\"\n")
            f.write("run_cmake_build_software \"$SOFTWARE_SRC\" \"$SOFTWARE_BUILD\"\n")
            f.write("move_dir \"$SOFTWARE_BUILD\" \"$ROOT_BUILD/software\"\n\n")
            f.write("log \"Done\"\n")

        # Make the script executable
        os.chmod(path, 0o755)
        print(f"Build script written to {path}")


    def write_root_readme(self, base_dir, project_name):
        path = os.path.join(base_dir, "README.md")
        with open(path, "w") as f:
            f.write(f"# 👷‍♂️ {project_name} FPGA + UART Platform\n\n")

            f.write("## 🚀 Combined Build (via `Build` script)\n")
            f.write("The top-level entry point is the **`Build`** script. It orchestrates:\n")
            f.write("- 🔬 FPGA toolchain (simulation → synth → PnR → bitstream → flash)\n")
            f.write("- 💻 UART software build (simulation, product, or test mode)\n\n")

            f.write("### Run Combined Build\n")
            f.write("```sh\n./Build [options]\n```\n\n")

            f.write("### ⚡ Available Flags\n")
            f.write("The `Build` script accepts the following options:\n\n")
            f.write("- `--sim` *(default)* → Build UART **simulation mode** (main executable)\n")
            f.write("- `--prod` → Build UART **shared product library** (`.so/.dll`)\n")
            f.write("- `--test` → Build UART **unit tests** with GoogleTest\n")
            f.write("- `--help` → Show usage help\n\n")
            f.write("If no flag is passed, it defaults to **simulation mode** (`--sim`).\n\n")

            f.write("### 🔧 Examples\n")
            f.write("```sh\n")
            f.write("./Build             # Build FPGA + UART in simulation mode (default)\n")
            f.write("./Build --prod      # Build FPGA + UART shared library (no simulation/test)\n")
            f.write("./Build --test      # Build FPGA + UART unit tests (with GoogleTest)\n")
            f.write("./Build --help      # Show usage info\n")
            f.write("```\n\n")

            f.write("After running, all build artifacts are placed under:\n")
            f.write("```\n/project_root/build/\n")
            f.write("  ├── gateware/   # FPGA build outputs (.json, .asc, .bin, logs)\n")
            f.write("  └── software/   # UART build outputs (libs, executables, tests)\n")
            f.write("```\n\n")

            f.write("## ⚙️ FPGA Module Build (Advanced)\n")
            f.write("If you want to build only the **FPGA gateware**:\n\n")
            f.write("```sh\ncd gateware\nmkdir -p build && cd build\ncmake ..\n")
            f.write("cmake --build . --target fpga -j4   # Simulation + synth + PnR + bitstream\n")
            f.write("cmake --build . --target flash      # Flash .bin to FPGA board\n```\n\n")

            f.write("### 🔍 Step Breakdown\n")
            f.write("- `sim` → RTL simulation\n")
            f.write("- `synth` → Yosys synthesis to JSON\n")
            f.write("- `pnr` → nextpnr place & route\n")
            f.write("- `bitstream` → Generate .bin with icepack\n")
            f.write("- `flash` → Upload to FPGA with iceprog\n\n")

            f.write("## 💻 Software Module Build (Advanced)\n")
            f.write("If you want to build only the **UART C++ software**:\n\n")
            f.write("```sh\ncd software\nmkdir -p build && cd build\n")
            f.write("cmake -DBUILD_PRODUCT=ON ..\ncmake --build . -j4   # Build shared UART library\n\n")
            f.write("cmake -DBUILD_SIMULATION=ON ..\ncmake --build . -j4   # Build simulation executable\n\n")
            f.write("cmake -DBUILD_TESTS=ON ..\ncmake --build . -j4\nctest --output-on-failure   # Run unit tests\n```\n\n")

            f.write("## 📂 Directory Structure\n")
            f.write("```\n/project_root\n")
            f.write("  ├── Build           # 🔧 Combined build script (entry point)\n")
            f.write("  ├── gateware/       # 📐 FPGA Verilog + CMakeLists\n")
            f.write("  ├── software/       # 💻 UART C++ code + CMakeLists\n")
            f.write("  └── README.md\n```\n")
            
        print(f"README.md written to {path}")